# Generated by Django 5.2.11 on 2026-02-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('periodicidade_meses', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
