# Generated by Django 5.2.11 on 2026-02-11 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateField()),
                ('proxima_dose', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinacoes', to='pets.pet')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccines.vacina')),
            ],
        ),
    ]
